set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_OPENCV -std=c++0x")
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64.*|AARCH64.*|arm64.*|ARM64.*)")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native") 
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mssse3")  
endif()
